### PR TITLE
Adding OctoEverywhere to the announcement feed!

### PR DESCRIPTION
**Pull request by QuinnDamerell**
Full Klilpper/Moonraker/Mainsail/Fluidd support is coming soon to OctoEverywhere.com!

### CODE REVIEW

**Comment by Arksine** [comment]
Looks good.  The readme should be fairly straight forward on how to create announcements, but feel free to ask if you have any questions.

**Comment by QuinnDamerell** [comment]
Thank you! If I understand correctly, this repo polls the other repos and builds a list of them, and then the moonraker clients pull that one rss freed correct? 

So if I add my service to the announcement service list locally and make a issue with the correct tag on my GitHub, I should show up in day or so?

**Comment by Arksine** [comment]
Very close.  Moonlight creates individual RSS feeds for each registered application.  It should take about 30 minutes to 1 hour after an issue is tagged with `announcement` reaches all users with an internet connection.

You are correct that the `octoeverywhere` feed can be configured in `moonraker.conf`.  It is also possible for your application to register itself via the [Add Feed API](https://moonraker.readthedocs.io/en/latest/web_api/#add-an-announcement-feed).  Once added via the API it is saved in the database and will persist unless removed.

**Comment by QuinnDamerell** [comment]
Great, thank you!

**Pull request merged**
